version: "3"

services:
  postgres:
    image: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

  broker_app:
    image: pactfoundation/pact-broker
    links:
      - postgres
      - pact_cli
    environment:
      PACT_BROKER_BASIC_AUTH_USERNAME: pact_username
      PACT_BROKER_BASIC_AUTH_PASSWORD: pact_password
      PACT_BROKER_DATABASE_USERNAME: postgres
        PACT_BROKER_DATABASE_PASSWORD: password
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_NAME: postgres
      PACT_BROKER_ALLOW_DANGEROUS_CONTRACT_MODIFICATION: "true"
      PACT_BROKER_PASSWORD_DIGEST: "false"
      PACT_BROKER_ORDER_DEPLOYMENTS_BY_CREATED_AT: "true"
      PACT_BROKER_WEBHOOK_EXEC_COMMAND: /scripts/webhook.ps1
    # Configure webhook
    volumes:
      - ./scripts:/scripts

  pact_cli:
    image: ruby:2.7-alpine
    depends_on:
      - broker_app
    command: sh -c "gem install pact_broker-client && sleep infinity"