name: Build and Publish

on:
  push:
    branches:
      - '*'

env:
  PACT_BROKER_PUBLISH_VERIFICATION_RESULTS: true

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build and Test
        run: |
          mvn verify

      - name: Publish Pact Contracts
        run: |
          mvn pact:publish
#      - name: Trigger Jenkins Build
#          run: |
#            curl -X POST "http://Taredel:C%21x6iffRT2%41localhost:9000/job/deployment_job_provider/build" --data-urlencode "delay=0sec"

  can-i-deploy:
    runs-on: ubuntu-latest
    publish: test
    steps:
      - uses: actions/checkout@v2
      - run: docker pull pactfoundation/pact-cli:latest
      - name: Can I deploy?
        run: make can_i_deploy